language: generic
dist: xenial
services:
  - xfvb

env:
  global:
    - INSTALL_EDM_VERSION=2.0.0
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - env: RUNTIME=2.7
    - env: RUNTIME=3.5
    - env: RUNTIME=3.6
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
    - "~/.cache"

before_install:
  - mkdir -p "${HOME}/.cache/download"
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - edm install -y wheel click coverage
install:
  - edm run -- python etstool.py install --runtime=${RUNTIME}
script:
  - edm run -- python etstool.py test --runtime=${RUNTIME}

after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
