[build-system]
requires = ["oldest-supported-numpy", "setuptools", "wheel"]
build-backend = 'setuptools.build_meta'

[tool.cibuildwheel]
skip = "pp* *-musllinux*"

[tool.cibuildwheel.macos]
archs = ["auto", "universal2"]

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]
