name: Test with PyPI

on: [pull_request, workflow_dispatch]

env:
  PYTHONUNBUFFERED: 1

jobs:

  # Test against PyPI packages
  test-with-pypi:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone the SciMath source
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package under test
        run: python -m pip install .
      - name: Run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir testdir
          cd testdir
          xvfb-run -a python -X faulthandler -m unittest discover -v scimath
      - name: Run tests (not Ubuntu)
        if: matrix.os != 'ubuntu-latest'
        run: |
          mkdir testdir
          cd testdir
          python -X faulthandler -m unittest discover -v scimath
