name: Test with EDM

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
  schedule:
    - cron:  '0 0 * * 5'

env:
  INSTALL_EDM_VERSION: 3.7.0

jobs:

  # Test against EDM packages
  test-with-edm:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        runtime: ['3.6', '3.8']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache EDM packages
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('etstool.py') }}
      - name: Set up EDM
        uses: enthought/setup-edm-action@v3
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python etstool.py install --runtime=${{ matrix.runtime }}
      - name: Run tests
        run: edm run -- python etstool.py test --runtime=${{ matrix.runtime }}
